frontend:
  listen_port: 8480
negative_caches:
  default:
    '400': 3s
    '404': 3s
    '500': 3s
    '502': 3s
caches:
  fs1:
    provider: filesystem
    filesystem:
      cache_path: /data/trickster
    index:
      max_size_objects: 512
      max_size_backoff_objects: 128
  mem1:
    provider: memory
    index:
      max_size_objects: 512
      max_size_backoff_objects: 128
  rds1:
    provider: redis
    redis:
      client_type: standard
      protocol: tcp
      endpoint: 'redis:6379'
tracing:
  std1:
    provider: stdout
    stdout:
      pretty_print: true
  otlp1:
    provider: otlp
    protocol: http
    endpoint: 'http://jaeger:4318/v1/traces'
backends:
  prom1: # prometheus cached with a memory cache, traces sent to stdout
    provider: prometheus
    origin_url: 'http://prometheus:9090'
    tracing_name: std1
    cache_name: mem1
  prom2: # prometheus cached with a filesystem cache, traces sent to Jaeger via OTLP/HTTP
    provider: prometheus
    origin_url: 'http://prometheus:9090'
    tracing_name: otlp1
    cache_name: fs1
  influx1: # influxdb cached with a memory cache, traces sent to Jaeger via OTLP/HTTP
    provider: influxdb
    origin_url: 'http://influxdb:8086'
    tracing_name: otlp1
    cache_name: mem1
    backfill_tolerance: 60s
  sim1: # simulated prometheus cached with a memory cache, traces sent to Jaeger via OTLP/HTTP
    provider: prometheus
    origin_url: 'http://mockster:8482/prometheus'
    tracing_name: otlp1
    cache_name: mem1
  sim2: # simulated prometheus cached with a Redis cache, traces sent to Jaeger via OTLP/HTTP
    provider: prometheus
    origin_url: 'http://mockster:8482/prometheus'
    tracing_name: otlp1
    cache_name: rds1
  rpc1: # memory reverse proxy cache of the byterange request simulation endpoint, traces sent to Jaeger via OTLP/HTTP
    provider: reverseproxycache
    origin_url: 'http://mockster:8482/byterange'
    tracing_name: otlp1
    cache_name: mem1
    paths:
      - path: /
        match_type: prefix
        handler: proxycache
        collapsed_forwarding: progressive
logging:
  log_level: info
metrics:
  listen_port: 8481
