version: "2"
run:
  tests: false
linters:
  enable:
    - dupl
    - staticcheck
    - wastedassign
    - unused
    - usetesting
    - usestdlibvars
    - unconvert
    - grouper
    - gocritic
    - revive
  disable:
    - errcheck
  settings:
    lll:
      line-length: 180
    staticcheck:
     checks:
       - all     # default
       - -ST1000 # default
       - -ST1003 # default
       - -ST1016 # default
       - -ST1020 # default
       - -ST1021 # default
       - -ST1022 # default
       - -QF1008 # prefer referencing embedded field by full reference
    gocritic:
     disabled-checks:
       - unslice # stylistic choice, ok with slice[:] references
       - ifElseChain # false positives / prefers switch statements
    revive:
      enable-all-rules: true
      rules:
        - name: unhandled-error
          arguments: # Allow skipping errors for the following functions
          - fmt.Print
          - fmt.Println
          - fmt.Printf
          - fmt.Fprintf
          - fmt.Fprint
          - strings.Builder.WriteString
          - os.Remove
          - encoding/pem.Encode
          - strings.Builder.WriteByte
          - strings.Builder.Write
          - text/tabwriter.Writer.Write
          - text/tabwriter.Writer.Flush
          - io.Writer.Write
          - io.Closer.Close
          - io.Copy
          - bytes.Buffer.Write
          - net/http.ResponseWriter.Write
          - mime/multipart.Writer.Close
          - mime/multipart.Writer.SetBoundary
          - net/http.Request.ParseForm
          - compress/gzip.Writer.Close
          - compress/flate.Writer.Write
          - compress/flate.Writer.Close
          - net/http.Request.ParseMultipartForm
        - name: exported
          arguments:
          - disableStutteringCheck
        - name: unused-parameter
          disabled: true # very noisy, lots of code with unused parameters; revisit later
        - name: line-length-limit
          disabled: true # prefer lll linter instead
        - name: add-constant
          disabled: true # very noisy, revisit later
        - name: empty-lines
          disabled: true # stylistic choice, ok with empty lines
        - name: cognitive-complexity
          disabled: true # too noisy, revisit later
        - name: time-naming
          disabled: true # stylistic choice, warnings not helpful
        - name: cyclomatic
          disabled: true # not helpful, perhaps later
        - name: max-public-structs
          disabled: true # not useful
        - name: function-result-limit
          disabled: true # not useful
        - name: confusing-results
          disabled: true # not useful
        - name: function-length
          disabled: true # not useful
        - name: unchecked-type-assertion
          disabled: true # not helpful, we have many of these; revisit later
        - name: unused-receiver
          disabled: true # not helpful, revisit later
        - name: flag-parameter
          disabled: true # not helpful, revisit later
        - name: unexported-naming
          disabled: true # not helpful, false positives
        - name: redefines-builtin-id
          disabled: true # not helpful
        - name: argument-limit
          disabled: true # not helpful
        - name: confusing-naming
          disabled: true # not helpful, revisit later
        - name: use-any
          disabled: true # too many hits, revisit in standalone PR
        - name: deep-exit
          disabled: true # not helpful
        - name: max-control-nesting
          disabled: true # not helpful
        - name: defer
          disabled: true # not helpful
        - name: unhandled-error
          disabled: true # TODO: come back to this
        - name: struct-tag
          disabled: true # not helpful
        - name: bare-return
          disabled: true # stylistic choice, ok with bare returns
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
