version: "2"
issues:
  new-from-rev: origin/main
  fix: true
run:
  tests: false
linters:
  enable:
    - dupl
    - lll
    - staticcheck
    - wastedassign
    - unused
    - usetesting
    - usestdlibvars
    - unconvert
    - grouper
    - gocritic
    - revive
    - gosec
    - misspell
    - whitespace
    - testifylint
    - promlinter
    - modernize
    - intrange
    - exptostd
    - errorlint
    - gocheckcompilerdirectives
    - mirror
    - importas
    - perfsprint
  disable:
    - errcheck
    - goconst # disable due to spate of findings unrelated to the PR coming through

formatters:
  enable:
  - gci
  - goimports
  - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/trickstercache) 
        - default
