/*
 * Copyright 2018 The Trickster Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package timeseries

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *TimeRangeQuery) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "stmt":
			z.Statement, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Statement")
				return
			}
		case "ex":
			err = z.Extent.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Extent")
				return
			}
		case "step":
			z.StepNS, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "StepNS")
				return
			}
		case "rl":
			z.RecordLimit, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "RecordLimit")
				return
			}
		case "tfd":
			err = z.TimestampDefinition.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "TimestampDefinition")
				return
			}
		case "cke":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "CacheKeyElements")
				return
			}
			if z.CacheKeyElements == nil {
				z.CacheKeyElements = make(map[string]string, zb0002)
			} else if len(z.CacheKeyElements) > 0 {
				for key := range z.CacheKeyElements {
					delete(z.CacheKeyElements, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "CacheKeyElements")
					return
				}
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "CacheKeyElements", za0001)
					return
				}
				z.CacheKeyElements[za0001] = za0002
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TimeRangeQuery) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "stmt"
	err = en.Append(0x86, 0xa4, 0x73, 0x74, 0x6d, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Statement)
	if err != nil {
		err = msgp.WrapError(err, "Statement")
		return
	}
	// write "ex"
	err = en.Append(0xa2, 0x65, 0x78)
	if err != nil {
		return
	}
	err = z.Extent.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Extent")
		return
	}
	// write "step"
	err = en.Append(0xa4, 0x73, 0x74, 0x65, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.StepNS)
	if err != nil {
		err = msgp.WrapError(err, "StepNS")
		return
	}
	// write "rl"
	err = en.Append(0xa2, 0x72, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt(z.RecordLimit)
	if err != nil {
		err = msgp.WrapError(err, "RecordLimit")
		return
	}
	// write "tfd"
	err = en.Append(0xa3, 0x74, 0x66, 0x64)
	if err != nil {
		return
	}
	err = z.TimestampDefinition.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "TimestampDefinition")
		return
	}
	// write "cke"
	err = en.Append(0xa3, 0x63, 0x6b, 0x65)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.CacheKeyElements)))
	if err != nil {
		err = msgp.WrapError(err, "CacheKeyElements")
		return
	}
	for za0001, za0002 := range z.CacheKeyElements {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "CacheKeyElements")
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "CacheKeyElements", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TimeRangeQuery) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "stmt"
	o = append(o, 0x86, 0xa4, 0x73, 0x74, 0x6d, 0x74)
	o = msgp.AppendString(o, z.Statement)
	// string "ex"
	o = append(o, 0xa2, 0x65, 0x78)
	o, err = z.Extent.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Extent")
		return
	}
	// string "step"
	o = append(o, 0xa4, 0x73, 0x74, 0x65, 0x70)
	o = msgp.AppendInt64(o, z.StepNS)
	// string "rl"
	o = append(o, 0xa2, 0x72, 0x6c)
	o = msgp.AppendInt(o, z.RecordLimit)
	// string "tfd"
	o = append(o, 0xa3, 0x74, 0x66, 0x64)
	o, err = z.TimestampDefinition.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "TimestampDefinition")
		return
	}
	// string "cke"
	o = append(o, 0xa3, 0x63, 0x6b, 0x65)
	o = msgp.AppendMapHeader(o, uint32(len(z.CacheKeyElements)))
	for za0001, za0002 := range z.CacheKeyElements {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TimeRangeQuery) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "stmt":
			z.Statement, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Statement")
				return
			}
		case "ex":
			bts, err = z.Extent.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Extent")
				return
			}
		case "step":
			z.StepNS, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StepNS")
				return
			}
		case "rl":
			z.RecordLimit, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RecordLimit")
				return
			}
		case "tfd":
			bts, err = z.TimestampDefinition.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "TimestampDefinition")
				return
			}
		case "cke":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CacheKeyElements")
				return
			}
			if z.CacheKeyElements == nil {
				z.CacheKeyElements = make(map[string]string, zb0002)
			} else if len(z.CacheKeyElements) > 0 {
				for key := range z.CacheKeyElements {
					delete(z.CacheKeyElements, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 string
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CacheKeyElements")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CacheKeyElements", za0001)
					return
				}
				z.CacheKeyElements[za0001] = za0002
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TimeRangeQuery) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Statement) + 3 + z.Extent.Msgsize() + 5 + msgp.Int64Size + 3 + msgp.IntSize + 4 + z.TimestampDefinition.Msgsize() + 4 + msgp.MapHeaderSize
	if z.CacheKeyElements != nil {
		for za0001, za0002 := range z.CacheKeyElements {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.StringPrefixSize + len(za0002)
		}
	}
	return
}
