/*
 * Copyright 2018 The Trickster Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package reserved defines the object-name prefixes that are reserved for
// configuration Trickster generates internally, so file-sourced configuration
// can be validated against them and each in-process producer owns a prefix.
package reserved

import (
	"slices"
	"strings"
)

const (
	// NamePrefixKubeGateway is the prefix for objects generated by the
	// Kubernetes Gateway/Ingress controller.
	NamePrefixKubeGateway = "kgw--"
)

var namePrefixes = []string{
	NamePrefixKubeGateway,
}

// NamePrefixes returns every reserved object-name prefix.
func NamePrefixes() []string {
	return slices.Clone(namePrefixes)
}

// IsNamePrefix reports whether prefix is one of the reserved prefixes.
func IsNamePrefix(prefix string) bool {
	return slices.Contains(namePrefixes, prefix)
}

// MatchNamePrefix returns the reserved prefix that name starts with, or an
// empty string when name is not reserved.
func MatchNamePrefix(name string) string {
	for _, p := range namePrefixes {
		if strings.HasPrefix(name, p) {
			return p
		}
	}
	return ""
}
