{
 "title": "Trickster Status",
 "description": "Demonstration Dashboard for Trickster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 0 },
   "content": "<img src=\"https://github.com/tricksterproxy/trickster/raw/master/docs/images/logos/trickster-logo.svg?sanitize=true\" height=\"90\" />\n"
  },
  {
   "title": "Up?",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"trickster\"}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Goroutine Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"trickster\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"trickster\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"trickster\"}",
     "legendFormat": "heap"
    }
   ]
  },
  {
   "title": "Trickster GC CPU Fraction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{job=\"trickster\"}"
    }
   ]
  },
  { "title": "Cache Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Time Series Cache Efficiency - All Caches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(trickster_proxy_requests_total{job=\"trickster\"}[1m])) by (cache_status)",
     "legendFormat": "{{cache_status}}"
    }
   ]
  },
  {
   "title": "Cache Utilization (# Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(trickster_cache_usage_bytes{job=\"trickster\"}) by (cache_name)",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache Utilization (# Objects)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(trickster_cache_usage_objects{job=\"trickster\"}) by (cache_name)",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache Object Evictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(delta(trickster_cache_events_total{event=\"eviction\",job=\"trickster\"}[1m])) by (cache_name)",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache Operations (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(delta(trickster_cache_operation_bytes_total{job=\"trickster\"}[1m])) by (cache_name, operation)",
     "legendFormat": "{{cache_name}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Cache Operations (Objects)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(delta(trickster_cache_operation_objects_total{job=\"trickster\"}[1m])) by (cache_name, operation)",
     "legendFormat": "{{cache_name}} - {{operation}}"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Trickster Frontend Responses by Origin & Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(trickster_frontend_requests_total{job=\"trickster\",job=\"trickster\"}[1m])) by (origin_name, http_status)",
     "legendFormat": "{{origin_name}} - {{http_status}}"
    }
   ]
  },
  {
   "title": "# Bytes Written to Frontend by Orgin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(trickster_frontend_written_bytes_total{job=\"trickster\",job=\"trickster\"}[1m])) by (origin_name)",
     "legendFormat": "{{origin_name}}"
    },
    {
     "expr": "sum(idelta(trickster_frontend_written_bytes_total{job=\"trickster\",job=\"trickster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "# Inbound Connections Handled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(trickster_proxy_requested_connections_total{job=\"trickster\"}[1m])) ",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(idelta(trickster_proxy_accepted_connections_total{job=\"trickster\"}[1m])) ",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(idelta(trickster_proxy_closed_connections_total{job=\"trickster\"}[1m])) ",
     "legendFormat": "closed"
    },
    {
     "expr": "sum(idelta(trickster_proxy_failed_connections_total{job=\"trickster\"}[1m])) ",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "# Backend Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(trickster_proxy_requests_total{job=\"trickster\"}[1m])) by (origin_name)",
     "legendFormat": "{{origin_name}}"
    }
   ]
  }
 ]
}