/*
 * Copyright 2018 The Trickster Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package engines

import (
	"bytes"
	"testing"

	"github.com/tinylib/msgp/msgp"
)

func TestMarshalUnmarshalHTTPDocument(t *testing.T) {
	v := HTTPDocument{
		StatusCode:    200,
		Status:        "200 OK",
		Headers:       map[string][]string{"Content-Type": {"text/plain"}},
		Body:          []byte("test body"),
		ContentLength: 9,
		ContentType:   "text/plain",
	}
	bts, err := v.MarshalMsg(nil)
	if err != nil {
		t.Fatal(err)
	}
	var v2 HTTPDocument
	left, err := v2.UnmarshalMsg(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after UnmarshalMsg(): %q", len(left), left)
	}

	if v2.StatusCode != 200 || v2.Status != "200 OK" || string(v2.Body) != "test body" || v2.ContentLength != 9 {
		t.Errorf("round-trip mismatch: got StatusCode=%d Status=%q Body=%q ContentLength=%d", v2.StatusCode, v2.Status, v2.Body, v2.ContentLength)
	}

	left, err = msgp.Skip(bts)
	if err != nil {
		t.Fatal(err)
	}
	if len(left) > 0 {
		t.Errorf("%d bytes left over after Skip(): %q", len(left), left)
	}
}

func BenchmarkMarshalMsgHTTPDocument(b *testing.B) {
	v := HTTPDocument{}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.MarshalMsg(nil)
	}
}

func BenchmarkAppendMsgHTTPDocument(b *testing.B) {
	v := HTTPDocument{}
	bts := make([]byte, 0, v.Msgsize())
	bts, _ = v.MarshalMsg(bts[0:0])
	b.SetBytes(int64(len(bts)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		bts, _ = v.MarshalMsg(bts[0:0])
	}
}

func BenchmarkUnmarshalHTTPDocument(b *testing.B) {
	v := HTTPDocument{}
	bts, _ := v.MarshalMsg(nil)
	b.ReportAllocs()
	b.SetBytes(int64(len(bts)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := v.UnmarshalMsg(bts)
		if err != nil {
			b.Fatal(err)
		}
	}
}

func TestEncodeDecodeHTTPDocument(t *testing.T) {
	v := HTTPDocument{
		StatusCode:  404,
		Status:      "404 Not Found",
		Body:        []byte("not found"),
		ContentType: "text/html",
	}
	var buf bytes.Buffer
	msgp.Encode(&buf, &v)

	m := v.Msgsize()
	if buf.Len() > m {
		t.Log("WARNING: TestEncodeDecodeHTTPDocument Msgsize() is inaccurate")
	}

	vn := HTTPDocument{}
	err := msgp.Decode(&buf, &vn)
	if err != nil {
		t.Error(err)
	}

	if vn.StatusCode != 404 || vn.Status != "404 Not Found" || string(vn.Body) != "not found" {
		t.Errorf("decoded HTTPDocument mismatch: got StatusCode=%d Status=%q Body=%q", vn.StatusCode, vn.Status, vn.Body)
	}

	buf.Reset()
	msgp.Encode(&buf, &v)
	err = msgp.NewReader(&buf).Skip()
	if err != nil {
		t.Error(err)
	}
}

func BenchmarkEncodeHTTPDocument(b *testing.B) {
	v := HTTPDocument{}
	var buf bytes.Buffer
	msgp.Encode(&buf, &v)
	b.SetBytes(int64(buf.Len()))
	en := msgp.NewWriter(msgp.Nowhere)
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.EncodeMsg(en)
	}
	en.Flush()
}

func BenchmarkDecodeHTTPDocument(b *testing.B) {
	v := HTTPDocument{}
	var buf bytes.Buffer
	msgp.Encode(&buf, &v)
	b.SetBytes(int64(buf.Len()))
	rd := msgp.NewEndlessReader(buf.Bytes(), b)
	dc := msgp.NewReader(rd)
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		err := v.DecodeMsg(dc)
		if err != nil {
			b.Fatal(err)
		}
	}
}
