#
# Trickster 2.0 Example Configuration File - Example Prometheus Accelerator
#
# To use this, run: trickster -config /path/to/simple.prometheus.yaml
#
# This file demonstrates a basic configuration to accelerate
# Prometheus queries using Trickster. More documentation is
# available at https://github.com/trickstercache/trickster/docs/
#
# Copyright 2018 The Trickster Authors
#

listeners:
  prom_port:
    protocol: http
    address: ""
    port: 9090

backends:
  default:
    # update FQDN and Port to work in your environment
    origin_url: 'http://prometheus:9090'
    provider: 'prometheus'
    listener_name: prom_port

logging:
  log_level: 'info'
