CREATE TABLE trips
(
    trip_id LONG,
    vendor_id SYMBOL,
    pickup_date DATE,
    pickup_datetime TIMESTAMP,
    pickup_epoch LONG,
    dropoff_date DATE,
    dropoff_datetime TIMESTAMP,
    store_and_fwd_flag INT,
    rate_code_id INT,
    pickup_longitude DOUBLE,
    pickup_latitude DOUBLE,
    dropoff_longitude DOUBLE,
    dropoff_latitude DOUBLE,
    passenger_count INT,
    trip_distance DOUBLE,
    fare_amount DOUBLE,
    extra DOUBLE,
    transit_tax DOUBLE,
    tip_amount DOUBLE,
    tolls_amount DOUBLE,
    ehail_fee DOUBLE,
    improvement_surcharge DOUBLE,
    total_amount DOUBLE,
    payment_type SYMBOL,
    trip_type INT,
    pickup SYMBOL,
    dropoff SYMBOL,
    cab_type SYMBOL,
    pickup_zone_gid INT,
    pickup_tract_label DOUBLE,
    pickup_borough_code INT,
    pickup_borough_name SYMBOL,
    pickup_tract_code SYMBOL,
    pickup_district_class SYMBOL,
    pickup_neighborhood_code SYMBOL,
    pickup_neighborhood_name SYMBOL,
    pickup_ward INT,
    dropoff_zone_gid INT,
    dropoff_tract_label DOUBLE,
    dropoff_borough_code INT,
    dropoff_borough_name SYMBOL,
    dropoff_tract_code SYMBOL,
    dropoff_district_class SYMBOL,
    dropoff_neighborhood_code SYMBOL,
    dropoff_neighborhood_name SYMBOL,
    dropoff_ward INT
)
TIMESTAMP(pickup_datetime)
PARTITION BY DAY
WAL
