name: FOSSA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.x"
      - run: go version
      # Runs a set of commands to initialize and analyze with FOSSA
      - name: run FOSSA analysis
        env:
          # FOSSA Push-Only API Token
          FOSSA_API_KEY: 'ff918866d6334ad92c36b407923205b4'
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$(go env GOPATH)/bin
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
          fossa init
          fossa analyze
